# -*- coding: utf-8 -*-
"""Task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odOiepN9TMjvHEmVoHpnkjwTr3QUF6BN
"""

def welcome_developer(name, role):
    badge = role.upper()
    print("==========================================")
    print(f"Welcome {name} to MediaWiki!")
    print(f"Role  : {role}")
    print(f"Badge : {badge}")
    print("==========================================")

def assign_task(role, project='MediaWiki'):
  match role:
    case 'Junior Developer':
            task = 'Fix a typo or formatting error in the codebase'
    case 'Active Developer':
            task = 'Review and test an open pull request'
    case 'Senior Developer':
            task = 'Fix a reported bug in the software'
    case _:
            task = 'Read the CONTRIBUTING file on GitHub'

  print(f"Project : {project}")
  print(f"Task    : {task}")
  return task

def check_skills(*skills):
  print("Skills registered:")
  for skill in skills:
    print(f"  - {skill}")
  print(f"Total skills: {len(skills)}")

print("==========================================")
print("   MEDIAWIKI — COMMUNITY MANAGER")
print("==========================================")
print("Project     : MediaWiki")
print("GitHub      : github.com/wikimedia/mediawiki")
print("Stars       : 4,200+")
print("Contributors: 1,000+ software developers")
print("==========================================")

joined_developers = []

while True:
  name = input("Enter developer name    : ")
  experience = input("Enter experience level : ")

  match experience:
      case 'beginner':
            role = 'Junior Developer'
      case 'intermediate':
            role = 'Active Developer'
      case 'advanced':
            role = 'Senior Developer'
      case 'expert':
            role = 'Lead Developer'
      case _:
            role = 'Observer'

  welcome_developer(name, role)
  assign_task(role)

  joined_developers.append(name)

  again = input("Add another developer? (yes/no): ")
  if again == 'no':
    break

joined_developers.append('Anonymous')
joined_developers.append('Vandal')
joined_developers.append('Sara')

print("------------------------------------------")
print("Scanning developer list...")
print("------------------------------------------")
for developer in joined_developers:
  if developer == 'Anonymous':
    print(f"Skipping {developer} — anonymous not allowed")
    continue
  if developer == 'Vandal':
    print("WARNING: Vandal detected! Stopping scan.")
    break

print(f"Developer verified: {developer}")


print("------------------------------------------")
print("Project name characters:")
for character in "MediaWiki":
    print(character)

def generate_report(project, *developers):
  print("==========================================")
  print("  MEDIAWIKI COMMUNITY REPORT")
  print("==========================================")
  print(f"  Project    : {project}")
  print(f"  Total      : {len(developers)} developers joined")
  print("------------------------------------------")
  print("  Developer List:")

  for developer in developers:
     print(f"    : {developer}")

  print("==========================================")

generate_report('MediaWiki', *joined_developers)
check_skills('PHP', 'JavaScript', 'MediaWiki API')